### ISSUE TITLE
Handle cases where archive is not present at default paths used.

### ISSUE THREAD

**Issue by qureship786** [tomaz/symbolicator#3]
If we are trying to symbolicate the crash logs using the 'symbolicator' on a machine which do not creates the archive but do have xcarchive (debug symbols) available in the same directory where crash log is present then how to use symbolicator in such cases ?

**Comment by tomaz** [comment]
Symbolicator uses Xcode archives to find dSYM bundles. Therefore the simplest way is to copy `~/Library/Developer/Xcode/Archives` folder to the computer where you're running symbolicator.

If you're concerned about hard drive space, you can only copy those `.xcarchive` bundles you need (just make sure you retain that intermediate `YYYY-MM-DD` folder structure - names are not important for symbolicator, just that there's some folder in between, you can also move all archives into the same folder as far as symbolicator is concerned)
