### ISSUE TITLE
"WARNING: Didn't find starting address"

### ISSUE THREAD

**Issue by fletcher** [tomaz/symbolicator#6]
For years I have struggled to find a good symbolication tool, but never had the time to write one myself.

I tried this one out this morning when my customized version of Simba failed to work, and I decided to find a better tool.

1. It *did* seem to a good job of automatically finding the dSYM (saving me the step of manually locating it and dragging it to where I need it.)

2. It *did not* work properly, giving this message "WARNING: Didn't find starting address for MultiMarkdown Composer" for each address to be symbolicated.  This happened on two separate crash reports (different users, same bug).

3. Manually following the instructions [here](https://stackoverflow.com/a/26461123/1400908) works.  The starting address is right where it's supposed to be, according to those instructions.

The relevant "Binary Images" section is (with the starting address of `0x106050000`:

	Binary Images:
	       0x106050000 -        0x106249ff7 +com.multimarkdown.composer4.mac (4.2.0 - 68) <A7FAE351-FBCE-3C3C-8D04-79EB09413C82> /Applications/MultiMarkdown Composer.app/Contents/MacOS/MultiMarkdown Composer
	       0x1096bf000 -        0x10970998f  dyld (519.2.1) <CD85EFBA-B9D6-3FD5-B777-A23B2DDEF192> /usr/lib/dyld
	       0x109d81000 -        0x10a06dfff  com.apple.driver.AppleIntelHD3000GraphicsGLDriver (10.4.12 - 10.0.4) <3C73B99B-AD1F-31E2-B5EC-32716FDE3E95> /System/Library/Extensions/AppleIntelHD3000GraphicsGLDriver.bundle/Contents/MacOS/AppleIntelHD3000GraphicsGLDriver

I would *love* it if you could fix this so that there is finally an automatic symbolication tool that works (I still don't understand why Xcode only does this for iOS, not macOS).  

If you need any further information, please let me know.

Otherwise, I'll try to fix it myself but it will probably be a few weeks before I would find the time to dig in and fix it.

Thanks!!

**Comment by tomaz** [comment]
That `+` sign in front of `com.multimarkdown.composer4.mac` could be the reason for not finding start address. Can you try deleting it from crashlog and try again to see what happens?

(Am not behind computer so can't test myself. But if it's just that it'll be quick fix - if still doesn't work could you send me full crash log file for closer inspection - if you don't want attaching it here, send it via email tomaz at gentlebytes.com)

**Comment by fletcher** [comment]
That did not fix it.

I'll email you crash log (probably nothing that secret in it, but it does come from a user, not me....)

**Comment by tomaz** [comment]
Ok. And no worries, it wouldn't be the first log I received. It doesn't contain any real personal info.

**Comment by tomaz** [comment]
Please try with fix - need to use newly introduced `--fuzzy` argument in order to have it check for this use case.

**Comment by fletcher** [comment]
That worked.  Thanks!
