### ISSUE TITLE
dyld Library not loaded

### ISSUE THREAD

**Issue by huang-kun** [tomaz/symbolicator#8]
I am using Xcode 10.1 to run this program. Build success, but it can't find the GBCli framework at runtime:

```
dyld: Library not loaded: @rpath/GBCli.framework/Versions/A/GBCli
  Referenced from: /Users/xxx/Library/Developer/Xcode/DerivedData/symbolicator-baonfvahfghmhlgjswguijwuaphj/Build/Products/Debug/symbolicator
  Reason: image not found
```

I have tried `pod install` (version: 1.4.0) and cleaned cached data, nothing changed.

**Comment by tomaz** [comment]
Strange... You don't have to run cocoapodals, all sources are already included with the repo.

Did you also try compiling&running the binary as is (without running cocoapods)?

**Comment by huang-kun** [comment]
Sorry, my mistake. I didn't notice this in README. It works by NOT running `pod install`! Thank you.
